#! /usr/bin/bash

case $1 in

a) 
ca65 -W 1 -l main.lst -o main.o -mm near -v \
    --cpu 6502 \
    --create-full-dep main.dep \
    --list-bytes 80 \
    --pagelength 36 \
    main.s
    ;;

c) 
    # cl65 -t atari -Ln main.lbl --listing main.lst --add-source -o main.xex main.s
    
echo " start compiling "


cl65 -C main.cfg --no-target-lib \
    -l main.asm -m main.map -o main.obj -Ln main.lbl \
    --cpu 6502 \
    main.s 2> err | tee out 

# --add-source --create-dep main.dep \
# -vm -v \
# -O0 -W1 -c -T -S \
echo " stop compiling "
    ;;

l)
ld65 -o main.bin -m main.map -Ln main.lbs -C main.cfg main.obj
    ;;

x)
    rm a main.obj main.dep main.asm main.map main.lbl out err c64/*
    ;;

esac

grep HEADER *.s | grep -v immu > words


